"""empty message

Revision ID: 6966cba43f6e
Revises: 8e475342f22a
Create Date: 2017-08-14 16:40:04.751059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6966cba43f6e'
down_revision = '8e475342f22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_webhook_event', sa.Column('remark', sa.String(), nullable=True))
    op.add_column('db_webhook_event', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_webhook_event', 'time')
    op.drop_column('db_webhook_event', 'remark')
    # ### end Alembic commands ###
