"""empty message

Revision ID: 8e475342f22a
Revises: e7590dbe1acb
Create Date: 2017-08-11 13:57:18.772904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e475342f22a'
down_revision = 'e7590dbe1acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_build', sa.Column('suppressed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_build', 'suppressed')
    # ### end Alembic commands ###
