"""empty message

Revision ID: ce2f10d7ea24
Revises: eb0c8c23d9b5
Create Date: 2017-08-09 23:18:31.361039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2f10d7ea24'
down_revision = 'eb0c8c23d9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_user', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_user', 'role')
    # ### end Alembic commands ###
