"""empty message

Revision ID: e6718ab0dca8
Revises: ce2f10d7ea24
Create Date: 2017-08-10 10:30:09.845476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6718ab0dca8'
down_revision = 'ce2f10d7ea24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_access_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key1', sa.String(), nullable=True),
    sa.Column('key2', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_access_key')
    # ### end Alembic commands ###
