"""empty message

Revision ID: eb0c8c23d9b5
Revises: eab27900506d
Create Date: 2017-08-09 10:26:12.516225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0c8c23d9b5'
down_revision = 'eab27900506d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_build', sa.Column('build_download_url', sa.String(), nullable=True))
    op.add_column('db_build', sa.Column('commit_date', sa.DateTime(), nullable=True))
    op.add_column('db_build', sa.Column('commit_message', sa.String(), nullable=True))
    op.add_column('db_build', sa.Column('commit_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_build', 'commit_url')
    op.drop_column('db_build', 'commit_message')
    op.drop_column('db_build', 'commit_date')
    op.drop_column('db_build', 'build_download_url')
    # ### end Alembic commands ###
